version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secretpass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth_service:
    build: ./auth_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./auth_service/:/app/
    ports:
      - 8003:8000
    environment:
      - JWT_SECRET=veryverysecretjwt
      - DATABASE_URL=postgresql://postgres:secretpass@db/user_db
    depends_on:
      db:
        condition: service_healthy

  movie_service:
    build: ./movie_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./movie_service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URL=postgresql://postgres:secretpass@db/movie_db
      - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/
    depends_on:
      db:
        condition: service_healthy

  cast_service:
    build: ./cast_service
    volumes:
      - ./cast_service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://postgres:secretpass@db/cast_db
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    ports:
      - 8000:8000
    volumes:
      - ./nginx/nginx_config.conf:/etc/nginx/conf.d/default.conf
      - ./static/v4:/var/www/html
    depends_on:
      - auth_service
      - cast_service
      - movie_service
  
  php:
    image: php:fpm-alpine
    volumes:
      - ./static/v4:/var/www/html

volumes:
  postgres_data: 
